# Generated by Django 2.2.1 on 2019-06-01 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelBooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=200)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelBooking.login')),
            ],
        ),
    ]
