# Generated by Django 2.1.8 on 2019-06-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelBooking', '0002_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginForm',
            fields=[
                ('login_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HotelBooking.login')),
            ],
            bases=('HotelBooking.login',),
        ),
        migrations.AddField(
            model_name='login',
            name='user_type',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
